### ISSUE TITLE
subAccount list query stopped working since 2022-09-20 20:00:00 UTC

### ISSUE THREAD

**Issue by arsmagic** [binance/binance-connector-php#10]
I am constantly monitoring new sub-users on hourly base via 
GET https://api.binance.com/sapi/v1/sub-account/list?page=1&limit=500&recvWindow=5000&timestamp=CURRENT_TIMESTAMP&signature=VALID_SIGNATURE.
Since 2022-09-20 20:00:00 UTC it stopped working, resulting in the following output:

Fatal error: Uncaught Binance\Exception\ClientException: GuzzleHttp\Exception\ClientException: Client error: `GET https://api.binance.com/sapi/v1/sub-account/list?page=1&limit=500&recvWindow=5000&timestamp=CURRENT_TIMESTAMP&signature=VALID_SIGNATURE` resulted in a `400 Bad Request` response: {"code":-10038,"msg":"Broker account is not supported."} in /MYPATH/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /MYPATH/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create() #1 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 /MYPATH/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run() #5 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /MYPATH/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /MYPATH/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(104): GuzzleHttp\Client->request() #11 /MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(98): Binance\APIClient->processRequest() #12 /MYPATH/vendor/binance/binance-connector-php/src/Binance/Spot/SubAccount.php(48): Binance\APIClient->signRequest() #13 /MYPATH/subuserminitor.php(28): Binance\Spot->subAccountList() #14 {main} in /MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php:106 Stack trace: #0 /MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(98): Binance\APIClient->processRequest() #1 /MYPATH/vendor/binance/binance-connector-php/src/Binance/Spot/SubAccount.php(48): Binance\APIClient->signRequest() #2 /MYPATH/subuserminitor.php(28): Binance\Spot->subAccountList() #3 {main} thrown in /MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php on line 106

Please help with the issue.

**Comment by arsmagic** [comment]
changing v1 to v3 helped.
