### ISSUE TITLE
subAccountUniversalTransferHistory (Master account) is not functioning

### ISSUE THREAD

**Issue by arsmagic** [binance/binance-connector-php#9]
GET https://api.binance.com/sapi/v1/sub-account/universalTransfer?page=1&recvWindow=5000&timestamp=1663519465973&signature=XXX results in in a `400 Bad Request` response: {"code":100001002,"msg":"Unsupported operation"} in MYPATH/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 MYPATH/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create() #1 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 MYPATH/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run() #5 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 MYPATH/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 MYPATH/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(104): GuzzleHttp\Client->request() #11 MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(98): Binance\APIClient->processRequest() #12 MYPATH/vendor/binance/binance-connector-php/src/Binance/Spot/SubAccount.php(553): Binance\APIClient->signRequest() #13 MYPATH/test4.php(14): Binance\Spot->subAccountUniversalTransferHistory() #14 {main} in MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php:106 Stack trace: #0 MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php(98): Binance\APIClient->processRequest() #1 MYPATH/vendor/binance/binance-connector-php/src/Binance/Spot/SubAccount.php(553): Binance\APIClient->signRequest() #2 MYPATH/test4.php(14): Binance\Spot->subAccountUniversalTransferHistory() #3 {main} thrown in MYPATH/vendor/binance/binance-connector-php/src/Binance/APIClient.php on line 106

**Comment by 2pd** [comment]
The error raised is because it's not supported for broker account.  You may wish to talk with the broker team and see if they have other solution.
